### ISSUE TITLE
Some tray icons are cropped vertically

### ISSUE THREAD

**Issue by voyagerok** [mate-desktop/mate-indicator-applet#29] opened 2018-06-14 06:32 UTC
#### Expected behaviour
Tray icons in indicator applet displayed normally.
#### Actual behaviour

Icons are cropped in vertical dimension.
https://imgur.com/S93LPqu
#### Steps to reproduce the behaviour
It can be reproduced in fresh install of Ubuntu Mate 18.04. Tray icons for Telegram Desktop or KeePassXC are cropped.

#### MATE general version

1.20.1
#### Package version

1.20.0
#### Linux Distribution

Ubuntu Mate 18.04
#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu-mate/+bug/1776835

**Comment by dmitry-kulikov** [comment] 2018-07-10 22:54
Probably duplicate of https://bugs.launchpad.net/ubuntu/+source/mate-indicator-applet/+bug/1733301.
I have the same versions of software and my problem https://imgur.com/a/riVaHXm: Google Chrome has too small icon; Hangouts - cropped; pgAdmin 4 - elephantine.

**Comment by selectiveduplicate** [comment] 2018-07-11 09:35
The default theme/s seems to have this type of problem. Open VLC and you'll see what I'm talking about. You can increase the panel size to adjust the icons, or you can use another theme.

**Comment by freespace** [comment] 2018-08-06 18:59
I ran into this issue with SpiderOakONE and patched my fork to resolve the issue by explicitly setting the icon sizes. It fixes the issue for me and would be interested if it works for others.

**Comment by dmitry-kulikov** [comment] 2018-08-08 00:34
@freespace I tried your fork and see improvements, but unfortunately it does not fix issue completely.
Before patch:
![before](https://user-images.githubusercontent.com/3766212/43809214-c96fb0dc-9ad2-11e8-979e-531d91265130.png)
After patch:
![after](https://user-images.githubusercontent.com/3766212/43809224-e07dbce2-9ad2-11e8-8d31-a19497831889.png)
SpiderOakONE - fixed, VLC - improved (cropped very slightly).
Big blue icon is pgAdmin 4, if someone is willing to work on this issue he can install it
`sudo apt install pgadmin4`
Green icon is Hangouts and it works very strange, sometimes cropped, sometimes tiny, no matter whether applet is patched.

**Comment by freespace** [comment] 2018-08-08 11:41
@dmitry-kulikov thanks for the feedback, I will have a look at pgadmin4 when I get a chance.

**Comment by lukefromdc** [comment] 2018-08-08 21:25
This looks like something is allocating a box  containing the icons at less then full panel size vertically. Maybe whatever sets a margin or padding in the sides of the applet is getting applied vertically? The margin looks about that size.  Does this happen in all themes?

**Comment by freespace** [comment] 2018-08-21 10:13
@dmitry-kulikov I have reproduced the problem on my end. I am currently trying to learn enough GTK+ to have useful debugging outputs.

**Comment by pfalcon** [comment] 2018-09-26 12:52
+1 on this issue. I upgraded from Ubuntu MATE 16.04 (was MATE 1.16 IIRC) to Ubuntu 18.04 (now MATE 1.20), and see slight vertical cropping on Ubuntu-standard blueman-applet, not counting KeepPassX.

Beyond that, keyboard typing break indicator is rather hosed, but there's a separate ticket for that, #21.

**Closed** 2019-05-14 18:56 UTC
Labels: confirmed
