### ISSUE TITLE
Volume control in indicator App has the wrong direction

### ISSUE THREAD

**Issue by jkpubsrc** [mate-desktop/mate-indicator-applet#71] opened 2021-03-02 09:21 UTC
## Description

If you open the indicator applet so that the indicator applet panel appears, volume control is implemented incorrectly.

## Expected behaviour

* on mouse wheel up: increase volume
* on mouse wheel down: decrease volume

## Actual behaviour

* on mouse wheel up: increase volume
* on mouse wheel down: decrease volume

## Steps to reproduce the behaviour

* move mouse wheel up / move mouse wheel down

## Package version

Indicator Applet v1.24.0

## Linux Distribution

Ubuntu Mate 20.04 LTS

**Comment by hugobuddel** [comment] 2021-05-11 14:42
This is a duplicate of #36. (I'm not affiliated with this package, just passing by.)

As a workaround, you can just hoover with the mouse cursor over the volume control (do not click it) and then scroll. Scrolling up increases the volume, and scrolling down decreases the volume. That is sufficent for me.

**Closed** 2021-08-25 13:19 UTC
